analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.51534
title: Tecants - Sustainable Business Design
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.695711133768782
  brandStrength: 0.4547018259763718
  rhythmicContrast: 0.9053707600105554
  brandColors:
    - '#ffffff'
    - '#7ac142'
    - '#515152'
    - '#878788'
    - '#ababab'
  lightness: 0.7554715741425753
purpose: []
favicon: null
name: Tecants
typography_spectrum: 0.41245
