name: Tecants
favicon: null
layout_spectrum: 0.51534
typography_spectrum: 0.41245
title: Tecants - Sustainable Business Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7ac142'
    - '#515152'
    - '#878788'
    - '#ababab'
  brandStrength: 0.45470182597637177
  lightness: 0.7554715741425753
  saturation: 0.695711133768782
  rhythmicContrast: 0.9053707600105554
purpose: []
